### PR TITLE
Move log messages to stderr

### PR DESCRIPTION
**Pull request by ZJaume**
Hi everyone, Prompsit fellow here!

The standard way of doing this in Unix is to use stderr. Otherwise, if the program is inside a pipe and fails due to wrong arguments for example, the help message gets scrambled with standard output and input. I also changed the `tmx_compiler.cc` because the method already has an output file, so I'm assuming messages have to go to stderr. But I don't know how that component works and what the printed information means.

### CODE REVIEW

**Comment by TinoDidriksen** [comment]
Error message should indeed go to stderr, but usage should not normally do so. It is important that `-? / -h / --help` output goes to stdout.

**Comment by ZJaume** [comment]
So I guess the `print_usage` should print to stderr only when errors occurr?

**Comment by TinoDidriksen** [comment]
Yeah, which is pretty simple to accomplish - just pass in stdout or stderr.

**Comment by ZJaume** [comment]
I found that bash commands print to stderr when `-?` but stdout with `-h`, is this ok for you or do you prefer `-?` also in stdout? I think `-?` is an error ans should go to stderr for the reasons i was pointing out at the beggining.

**Comment by TinoDidriksen** [comment]
I have merged an altered version of your suggestion.

**Comment by ZJaume** [comment]
Thank you! I was indeed waiting for your response to push that modications.

**Pull request closed without merging**
