### PR TITLE
Disjunct multiple FSTs encoded in the same at&t file

### LINKED ISSUE #56: Handle compiling multiple transducers in the same ATT file
Currently, lt-comp can only compile at&t files containing a single FST.
It would be better if it can also compile multiple disjunct FSTs encoded in the same at&t file.

Example:
```
$ cat transducer.att

--
0       1       a       b       0.000000
1       1.000000
--
0       1       b       c       0.000000
1       1.000000
--
```

The current behaviour is:
```
$ lt-comp lr transducer.att transducer.bin

Error: invalid format 'transducer.att'.
```

### PR DESCRIPTION
**Pull request by AMR-KELEG**
Fixes #56

### CODE REVIEW

**Comment by AMR-KELEG** [comment]
This patch will fail for the following input:
```
$ cat simple.att
0	1	a	b	0.000000
1	1.000000
--
0	1	b	c	0.000000
1	12.000000
--
```

**Comment by unhammer** [comment]
How does it fail?

**Comment by AMR-KELEG** [comment]
> How does it fail?

Well, a state with id 1 doesn't represent the same thing for different FSTs.

For example:
```
$ cat sample.att 
0       1       i       i
1       2       s       s
2       3       n       n
3       4       '       '
4       5       t       t
5       1.00
--
0       1       w       w
1       2       e       e
2       3       '       '
3       4       l       l
4       5       l       l
5       2.00

$ ./lttoolbox/lt-comp lr sample.att sample.bin
Warning: Multiple fsts in 'sample.att' will be disjuncted.
main@standard 6 10
```

Two problems will arise:
- The final state `5` will have two weights 1 & 2 !
- Strange inputs will get analysed:
```
$ echo "wen't" | ./lttoolbox/lt-proc sample.bin -W
^wen't/wen't<W:1.000000>$
```

**Comment by unhammer** [comment]
I don't think what this does is actually disjunction then, but some other kind of merge – with regular disjunction you shouldn't get an analysis for `wen't`. (Although it is disjunction if you first ensure the .att's have no overlapping state ids yourself … maybe that should be noted somewhere.)

**Comment by AMR-KELEG** [comment]
I am not sure I understand your comment.
But, the patch just ignores the -- tokens.
We need to use different ids for different FSTs but I am not sure where should this be done.
(A different command?)

**Comment by flammie** [comment]
The schoolbook algorithm to disjunction is to just add a new initial state and two epsilon arcs to previous start states of the disjunctees. To renumber the automata states you have to have distinct set of state numbers for both original automata, e.g. the LHS can retain its state numbers and RHS can just += largest state number to everything.

**Pull request merged**
