### PR TITLE
Allow weights on entries in lttoolbox XML

### PR DESCRIPTION
**Pull request by Techievena**
**GSoC Task 3**
Modify the DTD and parser to allow weights on entries in lttoolbox XML.

Status: _Under progress_

### CODE REVIEW

**Comment by Techievena** [comment]
@ftyers @flammie @TinoDidriksen how to test this PR?

**Comment by TinoDidriksen** [comment]
`xmllint --valid` or the `--dtdvalid` flag should help with that.

**Comment by Techievena** [comment]
Currently the output I am getting is:

```
abinash@change-the-world:~$ cat test.dix
<?xml version="1.0" encoding="UTF-8"?>
<dictionary>
	<alphabet>ABCDEFGHIJKLMNOPQRSTUVWXYZÀÁÂÄÅÆÇÈÉÊËÍÑÒÓÔÕÖØÙÚÜČĐŊŠŦŽabcdefghijklmnopqrstuvwxyzàáâäåæçèéêëíñòóôõöøùúüčđŋšŧž­-</alphabet>
<sdefs>
  <sdef n="n"     c="Noun"/>

  <sdef n="ma"    c="Masculine (animate)"/>
  <sdef n="mi"    c="Masculine (inanimate)"/>
  <sdef n="nt"    c="Neuter"/>
  <sdef n="f"     c="Feminine"/>

  <sdef n="sg"    c="Singular"/>
  <sdef n="du"    c="Dual"/>
  <sdef n="pl"    c="Plural"/>

  <sdef n="nom"   c="Nominative"/>
  <sdef n="gen"   c="Genitive"/>
  <sdef n="dat"   c="Dative"/>
  <sdef n="acc"   c="Accusative"/>
  <sdef n="ins"   c="Instrumental"/>
  <sdef n="loc"   c="Locative"/>
  <sdef n="voc"   c="Vocative"/>
</sdefs>
<pardefs>
  <pardef n="nan__n_ma">
    <e w="1.56"><p><l></l><r><s n="n"/><s n="ma"/><s n="sg"/><s n="nom"/></r></p></e>
    <e w="2.56"><p><l>a</l><r><s n="n"/><s n="ma"/><s n="sg"/><s n="gen"/></r></p></e>
    <e w="3.56"><p><l>ej</l><r><s n="n"/><s n="ma"/><s n="sg"/><s n="dat"/></r></p></e>
    <e w="4.56"><p><l>a</l><r><s n="n"/><s n="ma"/><s n="sg"/><s n="acc"/></r></p></e>
    <e w="5.56"><p><l>om</l><r><s n="n"/><s n="ma"/><s n="sg"/><s n="ins"/></r></p></e>
    <e w="6.56"><p><l>je</l><r><s n="n"/><s n="ma"/><s n="sg"/><s n="loc"/></r></p></e>
    <e w="7.56"><p><l>o</l><r><s n="n"/><s n="ma"/><s n="sg"/><s n="voc"/></r></p></e>

    <e w="8.56"><p><l>aj</l><r><s n="n"/><s n="ma"/><s n="du"/><s n="nom"/></r></p></e>
    <e w="9.56"><p><l>ow</l><r><s n="n"/><s n="ma"/><s n="du"/><s n="gen"/></r></p></e>
    <e w="10.56"><p><l>omaj</l><r><s n="n"/><s n="ma"/><s n="du"/><s n="dat"/></r></p></e>
    <e w="11.56"><p><l>ow</l><r><s n="n"/><s n="ma"/><s n="du"/><s n="acc"/></r></p></e>
    <e w="12.56"><p><l>omaj</l><r><s n="n"/><s n="ma"/><s n="du"/><s n="ins"/></r></p></e>
    <e w="13.56"><p><l>omaj</l><r><s n="n"/><s n="ma"/><s n="du"/><s n="loc"/></r></p></e>
    <e w="14.56"><p><l>aj</l><r><s n="n"/><s n="ma"/><s n="du"/><s n="voc"/></r></p></e>

    <e w="15.56"><p><l>ojo</l><r><s n="n"/><s n="ma"/><s n="pl"/><s n="nom"/></r></p></e>
    <e w="16.56"><p><l>ow</l><r><s n="n"/><s n="ma"/><s n="pl"/><s n="gen"/></r></p></e>
    <e w="17.56"><p><l>am</l><r><s n="n"/><s n="ma"/><s n="pl"/><s n="dat"/></r></p></e>
    <e w="18.56"><p><l>ow</l><r><s n="n"/><s n="ma"/><s n="pl"/><s n="acc"/></r></p></e>
    <e w="19.56"><p><l>ami</l><r><s n="n"/><s n="ma"/><s n="pl"/><s n="ins"/></r></p></e>
    <e w="20.56"><p><l>ach</l><r><s n="n"/><s n="ma"/><s n="pl"/><s n="loc"/></r></p></e>
    <e w="21.56"><p><l>ojo</l><r><s n="n"/><s n="ma"/><s n="pl"/><s n="voc"/></r></p></e>
  </pardef>
</pardefs>

  <section id="main" type="standard">
    <e lm="nan" w="22.56"><i>nan</i><par n="nan__n_ma"/></e>    
  </section>

</dictionary>
```
```
abinash@change-the-world:~$ lt-comp lr test.dix test-mor.bin 
main@standard 29 45
```
```
abinash@change-the-world:~$ lt-print test-mor.bin
0	1	n	n	22.560000	
1	2	a	a	22.560000	
2	3	n	n	22.560000	
3	4	ε	<n>	4.680000	
3	5	a	<n>	7.680000	
3	6	e	<n>	10.680000	
3	7	o	<n>	16.680000	
3	8	j	<n>	19.680000	
4	9	ε	<ma>	1.560000	
5	10	ε	<ma>	2.560000	
5	11	j	<ma>	8.560000	
5	12	m	<ma>	17.560000	
5	13	c	<ma>	20.560000	
6	14	j	<ma>	3.560000	
7	15	ε	<ma>	7.560000	
7	16	j	<ma>	15.560000	
7	17	m	<ma>	5.560000	
7	18	w	<ma>	9.560000	
8	19	e	<ma>	6.560000	
9	20	ε	<sg>	1.560000	
10	21	ε	<sg>	2.560000	
11	22	ε	<du>	34.240000	
12	23	ε	<pl>	17.560000	
12	24	i	<pl>	19.560000	
13	25	h	<pl>	20.560000	
14	23	ε	<sg>	3.560000	
15	26	ε	<sg>	7.560000	
16	22	o	<pl>	62.240000	
17	24	ε	<sg>	5.560000	
17	27	a	<du>	10.560000	
18	21	ε	<du>	9.560000	
18	21	ε	<pl>	16.560000	
19	25	ε	<sg>	6.560000	
20	28	ε	<nom>	51.360000	
21	28	ε	<gen>	28.680000	
21	28	ε	<acc>	34.680000	
22	28	ε	<nom>	51.360000	
22	28	ε	<voc>	87.360000	
23	28	ε	<dat>	21.120000	
24	28	ε	<ins>	25.120000	
25	28	ε	<loc>	27.120000	
26	28	ε	<voc>	87.360000	
27	28	j	<dat>	10.560000	
27	28	j	<ins>	12.560000	
27	28	j	<loc>	13.560000	
28	0.000000
```

What should the correct output look like? @ftyers @flammie @TinoDidriksen @unhammer

**Comment by flammie** [comment]
The most easiest I think would be like: 
```
0	1	n	n	0.0	
1	2	a	a	0.0	
2	3	n	n	22.560000	
3	4	ε	<n>	1.560000	
3	5	a	<n>	2.560000	
3	6	e	<n>	3.560000	
3	7	o	<n>	5.560000	
3	8	j	<n>	6.560000	
4	9	ε	<ma>	1.560000	
5	10	ε	<ma>	2.560000	
5	11	j	<ma>	8.560000	
5	12	m	<ma>	17.560000	
5	13	c	<ma>	20.560000	
6	14	j	<ma>	3.560000	
7	15	ε	<ma>	7.560000	
7	16	j	<ma>	15.560000	
7	17	m	<ma>	5.560000	
7	18	w	<ma>	9.560000	
8	19	e	<ma>	6.560000	
9	20	ε	<sg>	1.560000	
10	21	ε	<sg>	2.560000	
11	22	ε	<du>	8.560000	
12	23	ε	<pl>	17.560000	
12	24	i	<pl>	19.560000	
13	25	h	<pl>	20.560000	
14	23	ε	<sg>	3.560000	
15	26	ε	<sg>	7.560000	
16	22	o	<pl>	15.560000	
17	24	ε	<sg>	5.560000	
17	27	a	<du>	10.560000	
18	21	ε	<du>	9.560000	
18	21	ε	<pl>	16.560000	
19	25	ε	<sg>	6.560000	
20	28	ε	<nom>	15.560000	
21	28	ε	<gen>	16.560000	
21	28	ε	<acc>	18.560000	
22	28	ε	<nom>	15.560000	
22	28	ε	<voc>	21.560000	
23	28	ε	<dat>	17.560000	
24	28	ε	<ins>	19.560000	
25	28	ε	<loc>	20.560000	
26	28	ε	<voc>	21.560000	
27	28	j	<dat>	10.560000	
27	28	j	<ins>	12.560000	
27	28	j	<loc>	13.560000	
28	0.000000
```

So for each <e> the weight appears once on the path.

This way it adds up correctly in lookup/proc etc.

You can always optimise it later with a weight push algorithm as long as it's correct.

**Pull request merged**
