### PR TITLE
Merge Postgen, Intergen, and Transliteration

### PR DESCRIPTION
**Pull request by mr-martian**
Postgen, Intergen, and Transliteration all *should* do essentially the same thing.

Differences:
1. Intergen and Transliteration do not respect wblanks
2. Postgen and Intergen ignore anything not preceded by `~`
3. Postgen deletes `~` from the output
4. Postgen rereads the suffix of a match (presumably to allow for overlapping matches)

Of these, 1. is a bug, 2. would be eliminated by #42, and 4. is implemented badly (see #123) and I'm not convinced it's actually useful. That just leaves 3., which seems like it should just be a flag modifying 1 function rather than a difference between 3.

In this PR I merge all 3 modes into 1, with flags for 3. and 4., though 4. is currently not working.

I currently get correct output if I run any of the tests manually, but if I try to run `make test` it hangs on one of the lines in `PostgenerationWordboundBlankTest` until the pipe times out. Any help that can be given in terms of identifying the cause of this would be welcome.

### CODE REVIEW

**Comment by xavivars** [comment]
Intergen can probably be completely deleted. I introduce it to as a hack to avoid multiplying even more bidixes and langpairs in spa-cat, but everything that was done with it is now replaced with lex-tools, CG and preferences. I also think it had problems with other translation modes (docx or odt, if I remember properly), so I'm not sure id leave it around if no-one uses it

**Comment by unhammer** [comment]
Seems like this fixes https://github.com/apertium/lttoolbox/issues/145 =D 

That one hanging line is strange. I don't get the hang if I just run it from the command line.

**Comment by unhammer** [comment]
@mr-martian  Using daemon/client from https://wiki.apertium.org/wiki/Daemon#Flushing_examples_in_bash I do 

```
lt-comp lr tests/data/postgen.dix tests/data/postgen.bin
./daemon lttoolbox/lt-proc -p -z tests/data/postgen.bin 
```
in one terminal and then 
```
$ echo 'hi ~les la' |./client
hi le pe test la
$ echo '[[t:b:0]]~le[[/]] la n' |./client
```
↑ that last one hangs. Looks like it's simply not flushing or not outputting the final NUL?

**Comment by mr-martian** [comment]
Ok, so now it works for everything I can think of to pass in manually, both directly and via the daemon, but when I run the tests I'm still getting one hanging. Any ideas?

**Comment by unhammer** [comment]
It seems to work now?

**Comment by mr-martian** [comment]
For some reason when I run `make test` locally it fails, but no matter how exactly I try to reproduce it manually, it seems to work just fine.

**Comment by mr-martian** [comment]
Updated summary:

Merge postgeneration, intergeneration, and transliteration

* intergen and transliteration now respect wblanks
* postgen no longer rereads suffix of input (closes #123)
* postgen no long requires input to begin with `~` (closes #42)
* wblank manipulation can no longer produce nested blanks (closes #145)
* eliminate some dead code

**Pull request merged**
