### PR TITLE
Fix the analysis weight computation bug

### LINKED ISSUE #44: Weights are ignored in monolingual dictionary entries
Given the following paradigms and entries:

```
<pardef n="liv/e__vblex">
  <e>       <p><l>e</l>         <r>e<s n="vblex"/><s n="inf"/></r></p></e>
  <e>       <p><l>e</l>         <r>e<s n="vblex"/><s n="imp"/></r></p></e>
  <e>       <p><l>ed</l>        <r>e<s n="vblex"/><s n="pp"/></r></p></e>
  <e w="1"> <p><l>ing</l>       <r>e<s n="vblex"/><s n="pprs"/></r></p></e>
  <e w="3"> <p><l>ing</l>       <r>e<s n="vblex"/><s n="ger"/></r></p></e>
  <e w="2"> <p><l>ing</l>       <r>e<s n="vblex"/><s n="subs"/></r></p></e>
  <e>       <p><l>e</l>         <r>e<s n="vblex"/><s n="pres"/></r></p></e>
  <e>       <p><l>es</l>        <r>e<s n="vblex"/><s n="pres"/><s n="p3"/><s n="sg"/></r></p></e>
  <e>       <p><l>ed</l>        <r>e<s n="vblex"/><s n="past"/></r></p></e>
</pardef>
<pardef n="house__n">
  <e>       <p><l></l>          <r><s n="n"/><s n="sg"/></r></p></e>
  <e r="RL"><p><l>'s</l>        <r><s n="n"/><s n="sg"/><j/>'s<s n="gen"/></r></p></e>
  <e>       <p><l>s</l>         <r><s n="n"/><s n="pl"/></r></p></e>
  <e r="RL"><p><l>s'</l>        <r><s n="n"/><s n="pl"/><j/>'s<s n="gen"/></r></p></e>
</pardef>
```

```
<e lm="house" w="1">     <i>house</i><par n="house__n"/></e>
<e lm="house" w="2">     <i>hous</i><par n="liv/e__vblex"/></e>
```

lt-proc seems to ignore the weights for the entries:

```bash
$ echo "house" | lt-proc -wW eng-cat.automorf.bin
^house/house<n><sg><W:0.000000>/house<vblex><inf><W:0.000000>/house<vblex><pres><W:0.000000>/house<vblex><imp><W:0.000000>$
```

The expected result would be:

```bash
$ echo "house" | lt-proc -wW eng-cat.automorf.bin
^house/house<n><sg><W:1.000000>/house<vblex><inf><W:2.000000>/house<vblex><pres><W:2.000000>/house<vblex><imp><W:2.000000>$
```

However, the weights work fine when they are used inside a paradigm:

```bash
$ echo "housing" | lt-proc -wW eng-cat.automorf.bin
^housing/housing<n><sg><W:0.000000>/house<vblex><pprs><W:1.000000>/house<vblex><subs><W:2.000000>/house<vblex><ger><W:3.000000>$

```

### PR DESCRIPTION
**Pull request by AMR-KELEG**
When computing the overall weight of an analysis,
The weight of the final state was ignored.

### CODE REVIEW

**Comment by AMR-KELEG** [comment]
I tested the fix on the example provided here (https://github.com/apertium/lttoolbox/issues/44#issuecomment-476027261) and it worked.
Additionally, Note that the bug was actually there in the documentation of the tool http://wiki.apertium.org/wiki/User:Techievena/GSoC_2018_Work_Product_Submission.
(The weights computed are actually ignoring the weight of the final state)
```
$ echo "cats" | lt-proc -W test.bin
^cat/cat+n<W:6.353620>/cat+v<W:7.375045>$s
```

The correct weights should have been.
```
^cat/cat+n<W:6.879107>/cat+v<W:7.900532>$s
```

**Comment by TinoDidriksen** [comment]
That fix causes tests to fail. If the new weights are accurate, the tests need to be adjusted. If not, the code needs to be adjusted.

**Comment by MarcRiera** [comment]
I have tested this with apertium-eng, which includes the house<n>/house<vblex> case, and the results do not seem to change after building the branch with the fix:
```sh
$ echo "house" | lt-proc -wW eng.automorf.bin
^house/house<n><sg><W:0.000000>/house<vblex><inf><W:0.000000>/house<vblex><pres><W:0.000000>/house<vblex><imp><W:0.000000>$
```
Maybe something else is not working properly?

**Comment by AMR-KELEG** [comment]
> That fix causes tests to fail. If the new weights are accurate, the tests need to be adjusted. If not, the code needs to be adjusted.

I have manually computed the weights and I can assure that the fix is generating the correct weights.
Thus, I have updated the tests.

**Comment by unhammer** [comment]
I also manually checked against tests/data/cat-weigh.att – I believe the new tests are correct.

**Comment by TinoDidriksen** [comment]
There's still MarcRiera's issue - does this actually work for monolingual dicts now? As in, this might be a needed fix, but does it actually fix #44?

**Comment by AMR-KELEG** [comment]
> There's still MarcRiera's issue - does this actually work for monolingual dicts now? As in, this might be a needed fix, but does it actually fix #44?

No, It doesn't work for monolingual dicts.
I now believe that they are two different bugs.

I am currently debugging the processor using this file
```
<dictionary>
<alphabet>ÀÁÂÄÆÇÈÉÊËÌÍÎÏÑÒÓÔÖÙÚÛÜàáâäçèéêëìíîïñòóôöùúûüABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz</alphabet>
  <sdefs>
    <sdef n="n"   c="Noun"/> 
    <sdef n="np"  c="Proper name"/> 
    <sdef n="pr"  c="Preposition"/> 
    <sdef n="vblex"   c="Verb"/> 
    <sdef n="vbmod"   c="Modal verb"/> 
    <sdef n="vaux"  c="Auxiliary verb"/> 
    <sdef n="vbser"   c="Verb 'to be'"/> 
    <sdef n="vbhaver"   c="Verb 'to have'"/> 
    <sdef n="vbdo"  c="Verb 'to do'"/> 
    <sdef n="det"   c="Determiner"/> 
    <sdef n="predet"  c="Predeterminer"/> 
    <sdef n="prn"   c="Pronoun"/> 
    <sdef n="cnjcoo"  c="Coordinating conjunction"/> 
    <sdef n="cnjsub"  c="Subordinating conjunction"/> 
    <sdef n="p1"  c="First person"/> 
    <sdef n="p2"  c="Second person"/> 
    <sdef n="p3"  c="Third person"/> 
    <sdef n="attr"  c="Attributive"/> 
    <sdef n="sg"  c="Singular"/> 
    <sdef n="pl"  c="Plural"/> 
    <sdef n="sp"  c="Singular / plural"/> 
    <sdef n="m"   c="Masculine"/> 
    <sdef n="f"   c="Feminine"/> 
    <sdef n="mf"  c="Masculine / feminine"/> 
    <sdef n="nt"  c="Neuter"/> 
    <sdef n="mfn"   c="Masculine / feminine / neuter"/> 
    <sdef n="def"   c="Definite"/> 
    <sdef n="ind"   c="Indefinite"/> 
    <sdef n="ref"   c="Reflexive"/> 
    <sdef n="dem"   c="Demonstrative"/> 
    <sdef n="top"   c="Toponym"/> 
    <sdef n="al"  c="Altres (other)"/> 
    <sdef n="ant"   c="Anthroponym (first name)"/> 
    <sdef n="cog"   c="Cognomen (family name)"/> 
    <sdef n="prs"   c="Present subjunctive"/> 
    <sdef n="pres"  c="Present (tense)"/> 
    <sdef n="past"  c="Past"/> 
    <sdef n="pii"   c="Past indicative"/> 
    <sdef n="pis"   c="Past subjunctive"/> 
    <sdef n="imp"   c="Imperative"/> 
    <sdef n="inf"   c="Infinitive"/> 
    <sdef n="pp"  c="Past participle"/> 
    <sdef n="subs"  c="Verbal noun"/> 
    <sdef n="pprs"  c="Present participle"/> 
    <sdef n="ger"   c="Gerund"/> 
    <sdef n="cm"  c="Comma"/> 
    <sdef n="sent"  c="End of sentence marker"/> 
    <sdef n="quot"  c="Quote mark"/> 
    <sdef n="lquot"   c="Quote mark left"/> 
    <sdef n="rquot"   c="Quote mark right"/> 
    <sdef n="abbr"  c="Abbreviation"/> 
    <sdef n="adj"   c="Adjective"/> 
    <sdef n="adv"   c="Adverb"/> 
    <sdef n="preadv"  c="Pre-adverb"/> 
    <sdef n="rel"   c="Relative"/> 
    <sdef n="itg"   c="Interrogative"/> 
    <sdef n="cnjadv"  c="Adverbial conjunction"/> 
    <sdef n="comp"  c="Comparative"/> 
    <sdef n="sup"   c="Superlative"/> 
    <sdef n="pred"  c="Predicative"/> 
    <sdef n="ord"   c="Ordinal"/> 
    <sdef n="qnt"   c="Quantifier"/> 
    <sdef n="num"   c="Numeral / Number"/> 
    <sdef n="pron"  c="Pronoun"/> 
    <sdef n="ij"  c="Interjection"/> 
    <sdef n="lpar"  c="Left parenthesis"/> 
    <sdef n="rpar"  c="Right parenthesis"/> 
    <sdef n="apos"  c="Apostrophe"/> 
    <sdef n="percent"   c="Percentage"/> 
    <sdef n="guio"  c="Hyphen"/> 
    <sdef n="sep"   c="Seperable verb"/> 
    <sdef n="sint"  c="Synthetic adjective"/> 
    <sdef n="nom"   c="Nominative"/> 
    <sdef n="gen"   c="Genitive"/> 
    <sdef n="acr"   c="Acronym"/> 
    <sdef n="org"   c="Organisation"/> 
    <sdef n="tn"  c=""/> 
    <sdef n="nn"  c=""/> 
    <sdef n="aa"  c="Animate"/> 
    <sdef n="an"  c="Inanimate"/> 
    <sdef n="pos"   c="Possessive"/> 
    <sdef n="lquest"  c="left question mark"/> 
    <sdef n="obj"   c="Object"/> 
    <sdef n="subj"  c="Subject"/> 
    <sdef n="pers"  c="Personal (pronoun)"/> 
  </sdefs>
  <pardefs>
    <pardef n="liv/e__vblex">
      <e>       <p><l>e</l>         <r>e<s n="vblex"/><s n="inf"/></r></p></e>
      <e>       <p><l>e</l>         <r>e<s n="vblex"/><s n="imp"/></r></p></e>
      <e>       <p><l>ed</l>        <r>e<s n="vblex"/><s n="pp"/></r></p></e>
      <e w="1"> <p><l>ing</l>       <r>e<s n="vblex"/><s n="pprs"/></r></p></e>
      <e w="3"> <p><l>ing</l>       <r>e<s n="vblex"/><s n="ger"/></r></p></e>
      <e w="2"> <p><l>ing</l>       <r>e<s n="vblex"/><s n="subs"/></r></p></e>
      <e>       <p><l>e</l>         <r>e<s n="vblex"/><s n="pres"/></r></p></e>
      <e>       <p><l>es</l>        <r>e<s n="vblex"/><s n="pres"/><s n="p3"/><s n="sg"/></r></p></e>
      <e>       <p><l>ed</l>        <r>e<s n="vblex"/><s n="past"/></r></p></e>
    </pardef>
    <pardef n="house__n">
      <e>       <p><l></l>          <r><s n="n"/><s n="sg"/></r></p></e>
      <e r="RL"><p><l>'s</l>        <r><s n="n"/><s n="sg"/><j/>'s<s n="gen"/></r></p></e>
      <e>       <p><l>s</l>         <r><s n="n"/><s n="pl"/></r></p></e>
      <e r="RL"><p><l>s'</l>        <r><s n="n"/><s n="pl"/><j/>'s<s n="gen"/></r></p></e>
    </pardef>
  </pardefs>

  <e lm="house" w="1">     <i>house</i><par n="house__n"/></e>
  <e lm="house" w="2">     <i>hous</i><par n="liv/e__vblex"/></e>
</dictionary>
```

The sample transducer after compilation is:
```
0	1	h	h	0.000000	
1	2	o	o	0.000000	
2	3	u	u	0.000000	
3	4	s	s	0.000000	
4	5	e	e	0.000000	
4	6	e	e	1.000000	
4	7	i	e	0.000000	
5	8	ε	<vblex>	0.000000	
5	9	d	<vblex>	0.000000	
5	10	s	<vblex>	0.000000	
6	11	ε	<n>	0.000000	
6	12	s	<n>	0.000000	
7	13	n	<vblex>	0.000000	
8	14	ε	<inf>	0.000000	
8	14	ε	<imp>	0.000000	
8	14	ε	<pres>	0.000000	
9	14	ε	<pp>	0.000000	
9	14	ε	<past>	0.000000	
10	15	ε	<pres>	0.000000	
11	14	ε	<sg>	0.000000	
12	14	ε	<pl>	0.000000	
13	14	g	<pprs>	1.000000	
13	14	g	<ger>	3.000000	
13	14	g	<subs>	2.000000	
15	11	ε	<p3>	0.000000	
14	0.000000
```

So, the bug has nothing to do with the weights of the final state (which is 0 in this case).

I can update this pull request so that it can get merged and solve issue #44 in a new pull request.

**Pull request merged**
